extends GutTest

const MANIFEST_SCRIPT := preload("res://../src/providers/xr/aero_spatial_ui_xr_manifest.gd")
const PROVIDER_SCRIPT := preload("res://../src/providers/xr/aero_spatial_ui_xr_provider.gd")
const CONFIG_SCRIPT := preload("res://../src/providers/xr/aero_spatial_ui_xr_provider_config.gd")
const RUNTIME_BOUNDARY_SCRIPT := preload("res://../src/providers/xr/aero_spatial_ui_xr_runtime_boundary.gd")
const README_PATH := "res://../README.md"

func test_xr_manifest_locks_dependency_truth_and_runtime_ownership() -> void:
	var summary := MANIFEST_SCRIPT.ownership_summary()

	assert_eq(summary.get("repo_role"), "xr_provider_runtime")
	assert_eq(summary.get("provider_lane"), "xr")
	assert_eq(summary.get("contract_owner_package"), "aerobeat-input-core")
	assert_eq(summary.get("shared_helper_owner_package"), "aerobeat-spatial-ui-core")
	assert_true(summary.get("supported_source_variants", PackedStringArray()).has("xr_ray"))
	assert_true(summary.get("supported_source_variants", PackedStringArray()).has("xr_direct"))
	assert_true(summary.get("requires_packaged_shared_helpers", false))
	assert_true(summary.get("requires_consumer_world_hit_acquisition", false))
	assert_eq(summary.get("verification_status_default", ""), "unverified")
	assert_true(summary.get("ships_runtime_behavior", false))
	assert_true(summary.get("implements_xr_runtime_behavior", false))
	assert_false(summary.get("owns_contract_definition", true))
	assert_false(summary.get("owns_native_2d_bridge", true))
	assert_false(summary.get("owns_shared_helper_layer", true))
	assert_false(summary.get("owns_scene_specific_xr_rig", true))
	assert_false(summary.get("owns_world_hit_acquisition", true))

func test_xr_runtime_boundary_and_config_keep_existing_owners_and_non_goals() -> void:
	var provider = PROVIDER_SCRIPT.new()
	var config = CONFIG_SCRIPT.new()
	var boundary := provider.describe_boundary()
	var snapshot := config.to_boundary_snapshot()
	var dependencies := RUNTIME_BOUNDARY_SCRIPT.describe_dependencies()

	assert_true(boundary.get("implements_runtime_behavior", false))
	assert_true(boundary.get("owns_xr_provider_runtime", false))
	assert_false(boundary.get("owns_scene_specific_xr_rig", true))
	var interaction_summary: Dictionary = provider.describe_interaction_summary()
	assert_eq(str(interaction_summary.get("verification_status", "")), "unverified")
	assert_eq(str(interaction_summary.get("last_terminal_result", "not-empty")), "")
	assert_eq(str(interaction_summary.get("preferred_target_label", "not-none")), "none")
	assert_false(boundary.get("owns_world_hit_acquisition", true))
	assert_eq(boundary.get("expected_surface_type"), "world_3d")
	assert_eq(boundary.get("expected_verification_status"), "unverified")

	assert_eq(snapshot.get("provider_lane"), "xr")
	assert_eq(snapshot.get("extraction_phase"), "phase_3_first_xr_provider_extraction")
	assert_eq(snapshot.get("default_source_variant"), "xr_ray")
	assert_eq(snapshot.get("verification_status_default"), "unverified")

	assert_eq(dependencies.get("provider_lane"), "xr")
	assert_true(dependencies.get("supported_source_variants", PackedStringArray()).has("xr_ray"))
	assert_true(dependencies.get("supported_source_variants", PackedStringArray()).has("xr_direct"))
	assert_true(dependencies.get("requires_consumer_world_hit_acquisition", false))
	var helper_expectations := PackedStringArray(dependencies.get("helper_dependency_expectations", PackedStringArray()))
	assert_true(helper_expectations.has("XrUiInputAdapter"))
	assert_true(helper_expectations.has("AeroSpatialProjectionHelper"))
	assert_true(helper_expectations.has("AeroSpatialRectTargetResolver"))

	var non_goals: PackedStringArray = RUNTIME_BOUNDARY_SCRIPT.describe_non_goals()
	assert_true(non_goals.has("no canonical interaction contract types"))
	assert_true(non_goals.has("no native 2D bridge logic"))
	assert_true(non_goals.has("no shared helper-layer ownership"))
	assert_true(non_goals.has("no scene-specific XR rig setup"))
	assert_true(non_goals.has("no proof-host world-hit acquisition ownership"))
	assert_true(non_goals.has("no proof-scene composition ownership"))

	var readme := FileAccess.get_file_as_string(README_PATH)
	assert_string_contains(readme, "aerobeat-input-core")
	assert_string_contains(readme, "aerobeat-spatial-ui-core")
	assert_string_contains(readme, "XR lifecycle/runtime semantics")
	assert_string_contains(readme, "world-hit acquisition")
